"use client";

import { ArrowLeft, Download, FileJson } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import * as React from "react";

import { PageHeader } from "@/components/AppShell";
import {
  Badge,
  Button,
  ErrorState,
  FieldRow,
  Panel,
  PanelHeader,
  Skeleton,
} from "@/components/ui";
import { ApiError, api, formatBytes, formatDate, formatSeconds } from "@/lib/api";
import { SEVERITY_STYLES } from "@/lib/theme";
import type { AnalysisResult } from "@/lib/types";

function Section({
  index,
  title,
  children,
}: {
  index: number;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <Panel>
      <PanelHeader title={`${index}. ${title}`} />
      {children}
    </Panel>
  );
}

function yesNo(value: boolean | null | undefined) {
  if (value == null) return <span className="text-ink-faint">not reported</span>;
  return value ? (
    <Badge tone="warn">yes</Badge>
  ) : (
    <span className="text-ink-faint">no</span>
  );
}

export default function ReportDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params?.id;
  const [result, setResult] = React.useState<AnalysisResult | null>(null);
  const [error, setError] = React.useState<ApiError | null>(null);

  React.useEffect(() => {
    if (!id) return;
    let cancelled = false;
    (async () => {
      try {
        const payload = await api.result(id);
        if (!cancelled) setResult(payload);
      } catch (caught) {
        if (!cancelled)
          setError(
            caught instanceof ApiError
              ? caught
              : new ApiError("UNKNOWN", "Could not load this report.", 0),
          );
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id]);

  if (error) {
    return (
      <div className="mx-auto max-w-2xl p-4 md:p-6">
        <ErrorState title="Report unavailable" message={error.message} code={error.code} />
        <Link href="/reports" className="mt-3 inline-block">
          <Button variant="secondary" icon={<ArrowLeft className="h-4 w-4" />}>
            All reports
          </Button>
        </Link>
      </div>
    );
  }

  if (!result || !id) {
    return (
      <div className="mx-auto max-w-4xl space-y-3 p-4 md:p-6">
        <Skeleton className="h-9 w-64" />
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-36" />
        ))}
      </div>
    );
  }

  const { study, processing, segmentation, summary, discs, validated_metrics } = result;

  return (
    <div>
      <PageHeader
        title="Analysis Report"
        description={`${study.filename} · generated ${
          result.completed_at ? formatDate(result.completed_at) : "unknown"
        }`}
        actions={
          <>
            <a href={api.downloadUrl(id, "json")} download>
              <Button size="sm" variant="ghost" icon={<FileJson className="h-3.5 w-3.5" />}>
                JSON
              </Button>
            </a>
            <a href={api.downloadUrl(id, "md")} download>
              <Button size="sm" variant="primary" icon={<Download className="h-3.5 w-3.5" />}>
                Download Report
              </Button>
            </a>
          </>
        }
      />

      <div className="mx-auto max-w-4xl space-y-4 p-4 md:p-6">
        <div className="rounded-lg border border-seg-disc/25 bg-seg-disc/5 px-4 py-3">
          <p className="text-xs font-medium text-ink">
            Generated by an AI-assisted research pipeline.
          </p>
          <p className="mt-1 text-2xs leading-relaxed text-ink-muted">
            Results require review by a qualified radiologist. This is a research
            and educational prototype; it does not provide a clinical diagnosis and
            is not a medical device.
          </p>
        </div>

        <Section index={1} title="Study Information">
          <div className="px-4 py-3">
            <dl className="grid gap-x-8 sm:grid-cols-2">
              <FieldRow label="Filename" value={study.filename} />
              <FieldRow label="Format" value={study.format} mono />
              <FieldRow label="Size" value={formatBytes(study.size_bytes)} mono />
              <FieldRow
                label="Modality"
                value={
                  study.modality ? (
                    <span className="inline-flex items-center gap-1.5">
                      <span className="font-mono uppercase">{study.modality}</span>
                      <Badge tone="muted">{study.modality_source.replace(/_/g, " ")}</Badge>
                    </span>
                  ) : (
                    "not determinable"
                  )
                }
              />
              <FieldRow label="Sagittal slices" value={study.slice_count} mono />
              <FieldRow
                label="Native in-plane size"
                value={`${study.dimensions.join(" × ")} px`}
                mono
              />
              <FieldRow
                label="Native in-plane spacing"
                value={`${study.in_plane_spacing_mm.map((v) => v.toFixed(4)).join(" × ")} mm`}
                mono
              />
              <FieldRow label="Slice spacing" value={`${study.slice_spacing_mm} mm`} mono />
              <FieldRow label="Orientation" value={study.native_orientation} mono />
              <FieldRow
                label="Timepoint"
                value={`${result.timepoint.label} (single timepoint)`}
              />
            </dl>
          </div>
        </Section>

        <Section index={2} title="Processing Information">
          <div className="px-4 py-3">
            <dl>
              <FieldRow label="Preprocessing" value={processing.preprocessing} />
              <FieldRow label="Segmentation model" value={processing.segmentation_model} mono />
              <FieldRow label="Model provenance" value={processing.segmentation_source} />
              <FieldRow label="Post-processing" value={processing.postprocessing_method} />
              <FieldRow label="Compute device" value={processing.device.toUpperCase()} mono />
              <FieldRow
                label="Total duration"
                value={formatSeconds(processing.duration_seconds)}
                mono
              />
              <FieldRow label="Disc tracks found" value={processing.disc_tracks_found ?? "—"} mono />
            </dl>
            {Object.keys(processing.stage_durations).length > 0 ? (
              <div className="mt-2 flex flex-wrap gap-2">
                {Object.entries(processing.stage_durations).map(([stage, seconds]) => (
                  <Badge key={stage} tone="muted">
                    {stage.replace(/_/g, " ")} {seconds}s
                  </Badge>
                ))}
              </div>
            ) : null}
          </div>
        </Section>

        <Section index={3} title="Segmentation Overview">
          <div className="px-4 py-3">
            <dl>
              {segmentation.classes.map((cls) => (
                <FieldRow
                  key={cls.id}
                  label={cls.display_name}
                  value={
                    cls.validated_test_dice != null
                      ? `validated Dice ${cls.validated_test_dice.toFixed(5)}`
                      : "—"
                  }
                  mono
                />
              ))}
            </dl>
            <p className="mt-2 text-2xs leading-relaxed text-ink-faint">
              {segmentation.slice_count} slices segmented,{" "}
              {segmentation.informative_slice_count} carried enough predicted
              anatomy to measure on. {segmentation.note}
            </p>
          </div>
        </Section>

        <Section index={4} title="Disc-Level Analysis">
          {discs.length === 0 ? (
            <p className="px-4 py-4 text-xs text-ink-faint">
              No intervertebral disc was identified in this study.
            </p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-2xs">
                <thead>
                  <tr className="border-b border-line-subtle text-ink-faint">
                    <th scope="col" className="px-3 py-2">Disc</th>
                    <th scope="col" className="px-3 py-2">Pfirrmann</th>
                    <th scope="col" className="px-3 py-2">Modic (any)</th>
                    <th scope="col" className="px-3 py-2">Bulging</th>
                    <th scope="col" className="px-3 py-2">Narrowing</th>
                    <th scope="col" className="px-3 py-2">Herniation</th>
                    <th scope="col" className="px-3 py-2">Upper EP</th>
                    <th scope="col" className="px-3 py-2">Lower EP</th>
                    <th scope="col" className="px-3 py-2 text-right">Identity</th>
                  </tr>
                </thead>
                <tbody>
                  {discs.map((disc) => (
                    <tr key={disc.index} className="table-row">
                      <td className="px-3 py-2 font-mono text-ink">{disc.index}</td>
                      <td className="px-3 py-2 font-mono">
                        {disc.pfirrmann_grade ?? (
                          <span className="text-ink-faint">not reported</span>
                        )}
                      </td>
                      <td className="px-3 py-2">{yesNo(disc.modic_any)}</td>
                      <td className="px-3 py-2">{yesNo(disc.bulging)}</td>
                      <td className="px-3 py-2">{yesNo(disc.narrowing)}</td>
                      <td className="px-3 py-2">{yesNo(disc.herniation)}</td>
                      <td className="px-3 py-2">{yesNo(disc.upper_endplate)}</td>
                      <td className="px-3 py-2">{yesNo(disc.lower_endplate)}</td>
                      <td className="px-3 py-2 text-right font-mono">
                        {disc.identity_confidence != null
                          ? `${(disc.identity_confidence * 100).toFixed(0)}%`
                          : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <p className="border-t border-line-subtle px-4 py-2.5 text-2xs leading-relaxed text-ink-faint">
            Disc indices are integer positions counting upward from the most
            inferior disc. No anatomical level name is asserted, because the
            dataset does not state which vertebra is L5.
          </p>
        </Section>

        <Section index={5} title="Quantitative Measurements">
          {discs.length === 0 ? (
            <p className="px-4 py-4 text-xs text-ink-faint">Not available.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-2xs">
                <thead>
                  <tr className="border-b border-line-subtle text-ink-faint">
                    <th scope="col" className="px-3 py-2">Disc</th>
                    <th scope="col" className="px-3 py-2 text-right">Central height (mm)</th>
                    <th scope="col" className="px-3 py-2 text-right">Area (mm²)</th>
                    <th scope="col" className="px-3 py-2 text-right">AP extent (mm)</th>
                    <th scope="col" className="px-3 py-2 text-right">Disc/vertebra signal</th>
                    <th scope="col" className="px-3 py-2 text-right">Canal width (mm)</th>
                    <th scope="col" className="px-3 py-2 text-right">Slices</th>
                  </tr>
                </thead>
                <tbody>
                  {discs.map((disc) => {
                    const m = disc.measurements;
                    const cell = (v: number | null | undefined, digits = 3) =>
                      v == null ? <span className="text-ink-faint">—</span> : v.toFixed(digits);
                    return (
                      <tr key={disc.index} className="table-row font-mono">
                        <td className="px-3 py-2 text-ink">{disc.index}</td>
                        <td className="px-3 py-2 text-right">{cell(m.height_mm_central)}</td>
                        <td className="px-3 py-2 text-right">{cell(m.area_mm2, 1)}</td>
                        <td className="px-3 py-2 text-right">{cell(m.ap_extent_mm, 2)}</td>
                        <td className="px-3 py-2 text-right">
                          {cell(m.intensity_disc_vertebra_ratio, 4)}
                        </td>
                        <td className="px-3 py-2 text-right">
                          {cell(m.canal_width_at_disc_mm, 2)}
                        </td>
                        <td className="px-3 py-2 text-right">{disc.slices_present ?? "—"}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </Section>

        <Section index={6} title="Model-Derived Findings">
          <div className="space-y-2.5 px-4 py-3">
            <p className="text-2xs text-ink-faint">
              Each statement is generated by rule from the structured result. No
              language model is involved.
            </p>
            <ul className="space-y-2" role="list">
              {summary.findings.map((finding, i) => (
                <li key={i} className="flex gap-2.5">
                  <span
                    className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${SEVERITY_STYLES[finding.severity].dot}`}
                    aria-hidden
                  />
                  <span>
                    <span className="block text-2xs font-medium uppercase tracking-wide text-ink-faint">
                      {finding.category}
                    </span>
                    <span className="block text-xs leading-relaxed text-ink-muted">
                      {finding.text}
                    </span>
                  </span>
                </li>
              ))}
            </ul>
            {Object.keys(summary.unsupported_targets).length > 0 ? (
              <div className="rounded border border-line-subtle bg-surface-2/50 p-2.5">
                <p className="label-caps mb-1.5">Targets deliberately not reported</p>
                <ul className="space-y-1.5" role="list">
                  {Object.entries(summary.unsupported_targets).map(([name, reason]) => (
                    <li key={name} className="text-2xs leading-relaxed text-ink-faint">
                      <code className="text-ink-muted">{name}</code> — {reason}
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </div>
        </Section>

        <Section index={7} title="Limitations">
          <ul className="space-y-2 px-4 py-3 text-xs leading-relaxed text-ink-muted">
            <li>
              Validated performance was measured on a{" "}
              {validated_metrics.test_patients}-patient held-out test split, not on
              this study. Per-study accuracy is unknown.
            </li>
            <li>
              Segmentation macro foreground Dice{" "}
              {validated_metrics.segmentation_macro_foreground_dice}; disc indexing{" "}
              {validated_metrics.disc_indexing_percent}% (up from{" "}
              {validated_metrics.disc_indexing_baseline_percent}% before
              post-processing); end-to-end Pfirrmann QWK{" "}
              {validated_metrics.pfirrmann_qwk_end_to_end}.
            </li>
            <li>
              Disc height mean absolute error {validated_metrics.disc_height_mae_mm} mm
              and area mean absolute error {validated_metrics.disc_area_mae_mm2} mm²
              against ground-truth masks.
            </li>
            <li>
              Disc identity is derived from ordered geometry, not predicted directly.
              Identity support describes cross-slice tracking consistency, not
              clinical certainty.
            </li>
            <li>
              The nominal Modic type and spondylolisthesis are not reported: the
              former was never modelled, the latter had too few positive cases to
              validate.
            </li>
            <li>
              Pfirrmann grading applies to T2 and T2-SPACE series only, because the
              grade is defined on T2 signal.
            </li>
            <li>
              This is a single timepoint. No change over time is measured, and no
              postoperative or longitudinal assessment is provided, because the data
              this system was validated on contains no longitudinal follow-up.
            </li>
            <li>
              A segmentation or indexing metric measures agreement with one
              annotation protocol. It does not establish clinical effectiveness.
            </li>
          </ul>
        </Section>

        <Section index={8} title="Research Disclaimer">
          <p className="px-4 py-3 text-xs leading-relaxed text-ink-muted">
            {result.disclaimer}
          </p>
        </Section>
      </div>
    </div>
  );
}
